<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//div[@id='WorkOrderPriority']/div/div/input</description>
   <name>workorderpriority</name>
   <tag></tag>
   <elementGuidId>c6b078bc-df0d-4d06-9325-a960a4f15708</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='WorkOrderPriority']/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
